/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoliticaDeConfidentialitateRouteImport } from './routes/politica-de-confidentialitate'
import { Route as TermeniSiConditiiRouteImport } from './routes/termeni-si-conditii'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDeConfidentialitateRoute =
  PoliticaDeConfidentialitateRouteImport.update({
    id: '/politica-de-confidentialitate',
    path: '/politica-de-confidentialitate',
    getParentRoute: () => rootRouteImport,
  } as any)
const TermeniSiConditiiRoute = TermeniSiConditiiRouteImport.update({
  id: '/termeni-si-conditii',
  path: '/termeni-si-conditii',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/politica-de-confidentialitate': typeof PoliticaDeConfidentialitateRoute
  '/termeni-si-conditii': typeof TermeniSiConditiiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/politica-de-confidentialitate' | '/termeni-si-conditii'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/politica-de-confidentialitate' | '/termeni-si-conditii'
  id:
    '__root__' | '/' | '/politica-de-confidentialitate' | '/termeni-si-conditii'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliticaDeConfidentialitateRoute: typeof PoliticaDeConfidentialitateRoute
  TermeniSiConditiiRoute: typeof TermeniSiConditiiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-confidentialitate': {
      id: '/politica-de-confidentialitate'
      path: '/politica-de-confidentialitate'
      fullPath: '/politica-de-confidentialitate'
      preLoaderRoute: typeof PoliticaDeConfidentialitateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termeni-si-conditii': {
      id: '/termeni-si-conditii'
      path: '/termeni-si-conditii'
      fullPath: '/termeni-si-conditii'
      preLoaderRoute: typeof TermeniSiConditiiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliticaDeConfidentialitateRoute: PoliticaDeConfidentialitateRoute,
  TermeniSiConditiiRoute: TermeniSiConditiiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
